### PR TITLE
0.5.0 release news

### PR DESCRIPTION
**Pull request by Bertram25**
Feel free to have a look and try.

Also, the binaries will be needed before releasing.

### CODE REVIEW

**Comment by akien-mga** [comment]
It looks great! :-) I do want to see @Danimal696's artwork from https://github.com/OpenDungeons/OpenDungeons/issues/678 in there though, it's just too awesome to be missed :)

**Comment by Bertram25** [comment]
> It looks great! :-) I do want to see @Danimal696's artwork from OpenDungeons/OpenDungeons#678 in there though, it's just too awesome to be missed :)

I'll make it happen, right after updating the branches. ;) It'll replace the two screenshots at the beginning of the news with it. Those will be either moved below or removed.

**Comment by hwoarangmy** [comment]
BTW, how to test this ? Is there some way to try the website ?

**Comment by akien-mga** [comment]
> BTW, how to test this ? Is there some way to try the website ?

Yes, just pull @Bertram25's branch and open index.html in your favourite browser.
We only use static HTML so it does not need to set up a server to test the website.

**Comment by akien-mga** [comment]
> I'll make it happen, right after updating the branches. ;) It'll replace the two screenshots at the beginning of the news with it. Those will be either moved below or removed.

In place of the two screenshots at the beginning, I would use only one of the two pictures by @Danimal696, showing it like a banner (it would look better than having the two pictures in small next to one another as for the screenshots, that would somewhat defeat their "grandiose" purpose ;-)).

If we want to use the two pictures that @Danimal696 made, maybe you could put a first one just after the "OpenDungeons 0.5.0 is now released!", maybe the one with the rock troll :-D
Then leave the first batch of screenshots where they are, and add the awesome slaughter pictures at the end of the post.

I let you experiment, you're the master of the PR :)

**Comment by akien-mga** [comment]
@Bertram25 As you're busy with the Win32 binary, I'll do the changes that I see fit in another PR based on your branch, so that we can merge your PR and then mine when we want to press the "release" button :)

_Edit:_ Ah unless you're on it right now :)

**Comment by akien-mga** [comment]
For me this can be merged as soon as there is:
- at least one of the awesome pics by Danimal
- updated links to download 0.5.0 (+ comment out the line about the development snapshots).

**Comment by akien-mga** [comment]
BTW we don't have RSS feeds, so we don't have to make the release announcement 100% perfect right now in prevision of a sudden flux of readers; so we can publish it and edit it tomorrow if there are slight modifications to make.

**Comment by Bertram25** [comment]
All the requested changes will be addressed as soon as I've finished the zip. :)
I can't wait. ;)

**Comment by akien-mga** [comment]
> I can wait. ;)

Sure, I don't mean to press you, I'm just eager :-P It's not every day that we release such an awesome game :-D

**Comment by Bertram25** [comment]
Let's go! :D 
If anything, we'll do a quick-fixup afterwards.

**Comment by Bertram25** [comment]
> >    I can wait. ;)
> 
> Sure, I don't mean to press you, I'm just eager :-P It's not every day that we release such an awesome game :-D

Eh eh, actually, it was a typo, I fixed just afterward with "I can't wait" so I couldn't agree more. :)

**Pull request merged**
