### PR TITLE
Initial work for 0.6.0 release announcement

### PR DESCRIPTION
**Pull request by akien-mga**
It's not complete yet as screenshots are missing, but feel free to merge and continue working on it with pull requests, the news-0.6.0 branch is there for that purpose. The changes won't go live to the website until we merge the branch back into master.

### CODE REVIEW

**Comment by Bertram25** [comment]
Ok, let me try that. :)

**Comment by Bertram25** [comment]
Thanks for using a separate branch (as discussed.)

**Comment by Bertram25** [comment]
Looks fine to me, except for one thing. The release notes link url is wrong: (It's sublte)
good:
https://github.com/OpenDungeons/OpenDungeons/blob/0.6/RELEASE-NOTES.md
bad:
https://github.com/OpenDungeons/OpenDungeons/blob/0.6.0/RELEASE-NOTES.md

**Comment by Bertram25** [comment]
As said, we're lacking images but that's for another PR.

**Comment by akien-mga** [comment]
> Looks fine to me, except for one thing. The release notes link url is wrong: (It's sublte)

Actually it's correct; it's just that the 0.6.0 tag does not exist yet ;)

**Comment by Bertram25** [comment]
Ah, well, my bad in that case. :) Let's merge.

**Pull request merged**
