### PR TITLE
Use current banner logo as the header (centered) + misc css changes

### PR DESCRIPTION
**Pull request by akien-mga**
Also replace the "OD" logo with the official SVG version for now.

@Wout-van-Dongen To center the logo, I used the method described here: http://www.w3.org/Style/Examples/007/center.en.html#hv3
I have very little experience with proper CSS3, so if you don't like this solution feel free to improve it :-)

### CODE REVIEW

**Comment by Bertram25** [comment]
Looks good as for me. :)
While we're on details, what do you think about using a serif free font, like Arial for a start?

**Comment by akien-mga** [comment]
>  While we're on details, what do you think about using a serif free font, like Arial for a start?

Sounds like a good idea, I'll add a commit to do that.

**Comment by akien-mga** [comment]
Note that I don't have much experience with web design, so for now I mess a bit with the website as it's a WIP and we can make it look better with just a couple of modifications. @Wout-van-Dongen, since you probably have a broader design idea, feel free to undo some of my changes when you implement something better :)

**Comment by akien-mga** [comment]
Added some more quick and dirty improvements :)

**Comment by akien-mga** [comment]
Ping? :)

**Comment by Bertram25** [comment]
Oops, sorry for not answering earlier. The changes look good for me. Since @Wout-van-Dongen didn't answer earlier and because I think this is fine, let's merge.
He'll be able to fix whatever isn't fitting afterward.

**Pull request merged**
